name: memcached_benchmark

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  changes:
    if: github.repository == 'rex-rs/rex'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      bench: ${{ steps.filter.outputs.bench }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            bench:
              - 'tools/memcached_benchmark/**'

  build:
    needs: changes
    if: ${{ needs.changes.outputs.bench == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/memcached_benchmark

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: filter
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        with:
          filters: |
            bench:
              - 'tools/memcached_benchmark/**'
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0

      - name: Build
        run: nix develop --command bash -e -c 'cargo fmt --check --verbose && cargo build -r --verbose'

      - name: Run tests
        run: nix develop --command bash -e -c 'cargo test --verbose && cargo test -r --verbose'
