name: Meson Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    if: github.repository == 'rex-rs/rex'
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache Rex build directory
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-${{ runner.name }}-meson-${{ hashFiles('rex-native.ini', 'meson.build') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.name }}-meson

      - name: Setup Rex build directory
        run: meson setup --native-file rex-native.ini --reconfigure ./build

      - name: Compile Rex deps
        run: meson compile -C build build_deps

      - name: Compile Rex samples
        run: meson compile -C build

      - name: Run Rex sanity tests
        run: meson test -C build

