name: Meson Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: [main, ci]
    paths-ignore:
      - docs/**
      - tools/**
      - flake.nix
      - README.md
  pull_request:
    branches: [main]
    paths-ignore:
      - docs/**
      - tools/**
      - flake.nix
      - README.md

jobs:
  build_and_test:
    if: github.repository == 'rex-rs/rex'
    runs-on: [self-hosted, gentoo]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Rex build directory
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-${{ runner.name }}-meson-${{ hashFiles('rex-native.ini', 'meson.build') }}

      - name: Setup Rex build directory
        run: meson setup --native-file rex-native.ini --reconfigure ./build

      - name: Compile Rex deps
        run: meson compile -C build build_deps

      - name: Compile Rex samples
        run: meson compile -C build

      - name: Run Rex sanity tests
        run: meson test -C build
