name: Meson Build and Test via nix
on:
  push:
    branches: [main, ci]
    paths-ignore:
      - docs/**
      - tools/**
  pull_request:
    branches: [main]
    paths-ignore:
      - docs/**
      - tools/**

jobs:
  build_and_test:
    if: github.repository == 'rex-rs/rex'
    runs-on: [self-hosted, nix]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rex build directory
        run: meson setup --native-file rex-native.ini --reconfigure ./build
        shell: nix develop -v -L .#rex --command bash -e {0}

      - name: Compile Rex deps
        run: meson compile -C build build_deps
        shell: nix develop -v -L .#rex --command bash -e {0}

      - name: Compile Rex samples
        run: meson compile -C build
        shell: nix develop -v -L .#rex --command bash -e {0}
